name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:

  # Unit tests (phpunit)
  laravel-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 7.4
            env:
              LARAVEL: 8.*
          - php: 8.0
            env:
              LARAVEL: 8.*
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo
          tools: cs2pr
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${LARAVEL}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: ./vendor/bin/phpunit
      - name: Execute codesniffer tests
        run: './vendor/bin/phpcs --standard=./phpcs.xml ./'
